config/routes.rb
VotrMachine::Application.routes.draw do

  devise_for :users

  resources :rounds, :only => [:show, :vote] do
  	# member do
  	# 	post ':item_id', :action => 'vote', :as => 'vote'
  	# end
  	resources :items, :except => [:index, :show]
  end

  resources :manage

  match 'dashboard' => 'manage#index', :as => :user_root

  root :to => 'pages#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :percentage, :round_id, :title, :votes

  belongs_to :round

  before_save :recalculate_percentage

  private
  	def recalculate_percentage
  		self.percentage = self.votes.to_f / round.total_votes.to_f
  	end
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :end_time, :start_time, :total_votes

  has_many :items

  belongs_to :user

  before_create :generate_channel

  scope :current, lambda { 
    where("start_time <= ? and end_time > ?", DateTime.now, DateTime.now)
  }

  scope :past, lambda {
  	where("end_time < ?", DateTime.now)
  }

  scope :upcoming, lambda {
  	where("start_time > ?", DateTime.now)
  }

  private
 		def generate_channel
 			self.channel = SecureRandom.hex(12)
 		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :rounds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource_or_scope)
	  user_root_path
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  # GET /manage
  def index
    @items
  end

  def create
  end

  def update
    @round = Round.find(params[:round_id])
    unless @round.end_time.past?
      @items = @round.items.order("title")
      @item = @items.find(params[:id])
      @item.votes = @item.votes + 1
      @round.total_votes = @round.total_votes + 1

      if @item.save and @round.save
        @items = Round.find(params[:round_id]).items
        puts "Total votes: #{@round.total_votes}"

        publish = PUBNUB.publish({
          'channel' => @round.channel,
          'message' => { 'total_votes' => @round.total_votes, 'items' => @items },
          'callback' => lambda do |message|
            puts message
          end
        })

        render :status => 200, :json => { 'round' => @round, 'songs' => @items }
      end
    end
  end

  def new
  end

  def destroy
    @round = Round.find(params[:round_id])
    @item = @round.items.find(params[:id])

    @round.total_votes = @round.total_votes - @item.votes

    if @item.destroy && @round.save
      render :status => 200, :json => { 'round' => @round, 'songs' => @items }
    end
  end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  before_filter :authenticate_user!

  # GET /manage
  def index
    @rounds = current_user.rounds
  end

  def create
  end

  def edit
  end

  # GET /manage/:id
  def show
    @round = current_user.rounds.find(params[:id])
    @items = @round.items.order('votes DESC')
  end

  def new
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

	# GET /rounds
  def index
  end

  # GET /rounds/:id
  def show
  	@round = Round.includes(:items).find(params[:id])
  	@timer = @round.end_time - DateTime.now.to_i
  	@msg = { :items => @round.items, :round => @round, :total_votes => @round.total_votes }.to_json
  end

  # POST /rounds/:id/:item_id
	def vote
		@round = Round.find(params[:id])
		unless @round.end_time.past?
			@items = @round.items.order("title")
			@item = @items.find(params[:item_id])
			@item.votes = @item.votes + 1
			@round.total_votes = @round.total_votes + 1

			if @item.save and @round.save
        @items = Round.find(params[:id]).items
        puts "Total votes: #{@round.total_votes}"

        publish = PUBNUB.publish({
          'channel' => @round.channel,
          'message' => { 'total_votes' => @round.total_votes, 'items' => @items },
          'callback' => lambda do |message|
            puts message
          end
        })

        render :status => 200, :json => { 'round' => @round, 'songs' => @songs }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
	    when :notice then "alert alert-info"
	    when :success then "alert alert-success"
	    when :error then "alert alert-error"
	    when :alert then "alert"
	    when :warning then "alert"
    end
  end
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.haml
!!!
%html
	%head
		%title Votr Machine
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags

	%body
		.container
			= render :partial => "shared/navigation"
			= render :partial => "shared/flash_messages"
			= yield

app/views/pages/index.haml
%h1 Ok.

app/views/rounds/show.haml
.round-header
	%h1= @round.title
	%h1#clock.blue

- unless @round.items.blank?
	%ul.selections
		- @round.items.each do |i|
			%li[i]
				%h3
					= link_to "#{i.title}", round_item_path(@round, i), :class => "vote" 
					%small (<span class="votes">#{i.votes}</span> votes)
				.progress
					.outline
					.bar
- else
	%p This round doesn't seem to have any items...

<div pub-key="pub-ac572c62-7762-4e2e-9afb-a7620048edb0" sub-key="sub-f5b1501e-a0fc-11e1-a6de-d1b91d67d2fc" ssl="off" origin="pubsub.pubnub.com" id="pubnub"></div>
%script{ :src => "http://cdn.pubnub.com/pubnub-3.1.min.js" }
%script{:type => "text/javascript"}
	:plain
		$(function () {

			// Need to figure out a way to get serverSync working.
			$('#clock').countdown({until: #{@timer.to_i}, format: 'HMS', compact: true, onExpiry: disableVoting});
			update_votes(#{@msg});

			$('.vote').click(function(event) {
				event.preventDefault();
				var $link = $(this);

				if(my_votes <= 10) {
				  $.ajax({
							type: 'PUT',
							url: $link.attr('href'),
							success: function (response) {
							console.log("Vote placed.");
						},
						error: function (response) {
							console.log("Error: vote not placed.");
				  		alert("Vote could not be placed at this time.");
						}
					});
					my_votes = my_votes + 1;
				} else {
					alert("You've already voted too many times this round...");
				}
			});

			// LISTEN FOR MESSAGES
			PUBNUB.subscribe({
				channel    : '#{@round.channel}',

				restore    : false,

				callback   : update_votes,

				disconnect : function() {        // LOST CONNECTION.
					console.log("Disconnected from PubNub.");
				},

				reconnect  : function() {        // CONNECTION RESTORED.
					console.log("Reconnected to PubNub.");
				},

				connect    : function() {        // CONNECTION ESTABLISHED.
					console.log("Connected to PubNub.");
				}
			})
		});

app/views/shared/_flash_messages.haml
- flash.each do |key, value|
	%div{:class => "#{flash_class(key)} fade in"}
		%a.close{"data-dismiss" => "alert"}×
		= value

app/views/shared/_navigation.haml
.navigation
	%ul
		- if current_user # Navigation for signed in users.
			%li= link_to "Dashboard", user_root_path, :class => "btn-purple"
			%li= link_to "Create Poll", new_manage_path, :class => "btn-green"
			%li= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn-blue"
		- else
			%li= link_to "Home", root_path, :class => "btn-purple"
			%li= link_to "About", "#", :class => "btn-yellow"
			%li= link_to "Sign In", new_user_session_path, :class => "btn-blue"